//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrairieMessages
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int UID { get; set; }
        public string MessageTitle { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string MessageDescription { get; set; }
        public string MessageAuthor { get; set; }
        public string MessageHardCopy { get; set; }
        public string Series { get; set; }
        public string VideoFile { get; set; }
        public string mp3File { get; set; }
    }
}
